"""The line that splits a CRM export from Ranger's own context.

Account notes are generated by `build_vault.py` from a CRM export. Ranger now
appends to them, which means one file holds two things with different owners and
different lifetimes: everything above the marker belongs to the export and is
regenerable, everything below belongs to Ranger and is not.

Without the split, a future export means hand-reconciling 69 notes. With it, a
refresh replaces the half above and leaves the half below alone.

**The token is `<!-- ranger:below`, counted by occurrence, and everything from
that byte onward is the below-half.** The rest of the comment and the
`## Ranger Context` heading are editable prose. That is deliberate: the operator
reads these notes in Obsidian and will reflow a comment or reword it eventually,
and a split that depended on the exact surrounding text would break silently the
first time they did. Producer and consumer sharing a constant is fine. Producer
and consumer sharing an assumption about the text around it is the bug that
flattened the training notebook.

Absent or duplicated, the answer is the same: refuse. A note with no marker is a
note this code does not understand, and guessing where the line should go is how
a tool that may only append ends up rewriting an export.
"""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path
from typing import Any, Iterable

#: The whole rule, in one string. Everything else here is about occurrences of
#: this and nothing about what follows it.
TOKEN = "<!-- ranger:below"

#: What the migration writes. Only the first line is load-bearing.
BLOCK = """\
<!-- ranger:below — everything above this line is CRM export, regenerable.
     Ranger appends only below. Nothing above is ever modified. -->

## Ranger Context
"""

#: The activity heading shape the account notes already use, so the parsers in
#: accounts.py keep working over what Ranger writes.
ENTRY = "### {when} | {note} | {source}"

#: A heading and blank lines are what the migration itself leaves behind. Only
#: something past them counts as Ranger having written anything.
_EMPTY_BELOW = re.compile(r"^\s*(##[^\n]*\n)?\s*$")


class MarkerError(Exception):
    """The marker is missing, duplicated, or the file changed underneath us."""


def count(text: str) -> int:
    return text.count(TOKEN)


def split(text: str) -> tuple[str, str]:
    """(above, below), or MarkerError saying which way it is wrong.

    `below` starts at the token itself, so the marker travels with the half that
    Ranger owns and rewriting the half above never has to reproduce it.
    """
    found = count(text)
    if found == 0:
        raise MarkerError(
            f"no {TOKEN!r} marker in this note. Ranger appends below the marker and "
            "will not create one on the fly: a note with no marker is a note this does "
            "not understand. Run: ranger accounts migrate"
        )
    if found > 1:
        raise MarkerError(
            f"{found} {TOKEN!r} markers in this note, and there must be exactly one. "
            "Two markers means two places to append and no way to tell which half is "
            "the export."
        )
    at = text.index(TOKEN)
    return text[:at], text[at:]


def marked(text: str) -> bool:
    return count(text) == 1


def has_context(text: str) -> bool:
    """Has Ranger written anything into this note yet?

    A migrated note that nobody has appended to has a marker and a heading and
    nothing else. That is not context, and treating it as such would make the
    rebuild guard refuse a vault where Ranger has done nothing.
    """
    try:
        _, below = split(text)
    except MarkerError:
        return False
    body = below.split("-->", 1)[-1] if "-->" in below else below
    return not _EMPTY_BELOW.match(body)


def digest(text: str) -> str:
    """Of the bytes above the marker. The thing the append guard compares."""
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def entry(note: str, source: str, when: date | None = None) -> str:
    """One appended block, in the format the note already uses.

    Newlines are stripped out of the heading rather than escaped: a note
    containing one would produce a second heading and a fragment that parses as
    a different activity.
    """
    line = ENTRY.format(
        when=(when or date.today()).isoformat(),
        note=" ".join(str(note).split()),
        source=" ".join(str(source).split()),
    )
    return f"\n{line}\n"


# -- the migration ----------------------------------------------------------


@dataclass
class Migration:
    """What a run did, and what it refused to touch."""

    migrated: list[str] = field(default_factory=list)
    already: list[str] = field(default_factory=list)
    refused: list[tuple[str, str]] = field(default_factory=list)

    @property
    def changed(self) -> int:
        return len(self.migrated)

    def describe(self) -> str:
        lines = [
            f"{len(self.migrated)} migrated, {len(self.already)} already marked",
        ]
        for name, why in self.refused:
            lines.append(f"  refused {name}: {why}")
        return "\n".join(lines)


def migrate(vault: Any, folder: Path, *, dry_run: bool = False) -> Migration:
    """Append the marker to every account note that has not got one.

    Idempotent by construction: a note is migrated only when it has exactly zero
    markers, so a second run finds one everywhere and does nothing. A note with
    two is refused rather than repaired, because there is no way to know which
    of them the operator meant.
    """
    report = Migration()
    for note in sorted(folder.rglob("*.md")):
        if not note.is_file():
            continue
        name = note.name
        try:
            text = note.read_text(encoding="utf-8")
        except OSError as exc:
            report.refused.append((name, f"could not be read: {exc}"))
            continue

        found = count(text)
        if found == 1:
            report.already.append(name)
            continue
        if found > 1:
            report.refused.append((name, f"{found} markers already"))
            continue

        if not dry_run:
            separator = "" if text.endswith("\n\n") else "\n" if text.endswith("\n") else "\n\n"
            note.write_text(text + separator + BLOCK, encoding="utf-8")
        report.migrated.append(name)
    return report


# -- the rebuild guard ------------------------------------------------------


def notes_with_context(folder: Path) -> list[tuple[str, int]]:
    """Every account note holding Ranger context, with how many lines of it.

    What `build_vault.py` has to consult before it regenerates anything. The
    operator's intention not to rebuild is the safety property today, and
    intention is not enforcement: every real bug in this build came from
    something that was true by intent rather than in code.
    """
    holding: list[tuple[str, int]] = []
    for note in sorted(folder.rglob("*.md")):
        if not note.is_file():
            continue
        try:
            text = note.read_text(encoding="utf-8")
        except OSError:
            # Unreadable counts as holding. Fail closed: a note that cannot be
            # checked is not a note that has been cleared.
            holding.append((note.name, -1))
            continue
        if not has_context(text):
            continue
        _, below = split(text)
        body = below.split("-->", 1)[-1] if "-->" in below else below
        holding.append((note.name, len([ln for ln in body.splitlines() if ln.strip()])))
    return holding


def rebuild_refusal(folder: Path) -> str:
    """The message build_vault.py prints instead of running, or "" to proceed."""
    holding = notes_with_context(folder)
    if not holding:
        return ""
    lines = [
        f"REFUSING to rebuild: {len(holding)} account notes hold Ranger context "
        "below the marker, and a rebuild would destroy it.",
        "",
    ]
    for name, count_of in holding[:10]:
        detail = "unreadable" if count_of < 0 else f"{count_of} lines"
        lines.append(f"  {name}  ({detail})")
    if len(holding) > 10:
        lines.append(f"  ... and {len(holding) - 10} more")
    lines += [
        "",
        "Nothing above the marker is at risk; everything below it is. If you have",
        "decided to lose it, pass --rebuild-destroys-ranger-notes and confirm at",
        "the prompt.",
    ]
    return "\n".join(lines)
