"""The line that splits a CRM export from Ranger's own context.

Account notes are generated by `build_vault.py` from a CRM export. Ranger now
appends to them, which means one file holds two things with different owners and
different lifetimes: everything above the marker belongs to the export and is
regenerable, everything below belongs to Ranger and is not.

Without the split, a future export means hand-reconciling 69 notes. With it, a
refresh replaces the half above and leaves the half below alone.

**The token is `<!-- ranger:below`, counted by occurrence, and everything from
that byte onward is the below-half.** The rest of the comment and the
`## Ranger Context` heading are editable prose. That is deliberate: the operator
reads these notes in Obsidian and will reflow a comment or reword it eventually,
and a split that depended on the exact surrounding text would break silently the
first time they did. Producer and consumer sharing a constant is fine. Producer
and consumer sharing an assumption about the text around it is the bug that
flattened the training notebook.

Absent or duplicated, the answer is the same: refuse. A note with no marker is a
note this code does not understand, and guessing where the line should go is how
a tool that may only append ends up rewriting an export.
"""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path
from typing import Any, Iterable

#: The whole rule, in one string. Everything else here is about occurrences of
#: this and nothing about what follows it.
TOKEN = "<!-- ranger:below"

#: The same token, for the write path, which is binary from end to end.
#:
#: The account write path's promise is byte identity, so no step in it gets to
#: reinterpret bytes. `Path.write_text` opens in text mode: on Windows it turns
#: every `\n` into `\r\n`, so a file that already used `\r\n` comes back as
#: `\r\r\n`, and `read_text` then folds that to `\n\n`. The bytes above the
#: marker no longer match the bytes that were read, the guard refuses, and it
#: refuses because the writer corrupted a file that was fine. On Linux nothing
#: translates and it round-trips, so the suite agreed with itself and with
#: nothing outside.
TOKEN_BYTES = TOKEN.encode("utf-8")

#: What the migration writes. Only the first line is load-bearing.
BLOCK = """\
<!-- ranger:below — everything above this line is CRM export, regenerable.
     Ranger appends only below. Nothing above is ever modified. -->

## Ranger Context
"""

#: The activity heading shape the account notes already use, so the parsers in
#: accounts.py keep working over what Jarvis writes.
ENTRY = "### {when} | {note} | {source}"

#: A heading and blank lines are what the migration itself leaves behind. Only
#: something past them counts as Jarvis having written anything.
_EMPTY_BELOW = re.compile(r"^\s*(##[^\n]*\n)?\s*$")


class MarkerError(Exception):
    """The marker is missing, duplicated, or the file changed underneath us."""


def count(text: str) -> int:
    return text.count(TOKEN)


def split(text: str) -> tuple[str, str]:
    """(above, below), or MarkerError saying which way it is wrong.

    `below` starts at the token itself, so the marker travels with the half that
    Jarvis owns and rewriting the half above never has to reproduce it.
    """
    found = count(text)
    if found == 0:
        raise MarkerError(
            f"no {TOKEN!r} marker in this note. Jarvis appends below the marker and "
            "will not create one on the fly: a note with no marker is a note this does "
            "not understand. Run: ranger accounts migrate"
        )
    if found > 1:
        raise MarkerError(
            f"{found} {TOKEN!r} markers in this note, and there must be exactly one. "
            "Two markers means two places to append and no way to tell which half is "
            "the export."
        )
    at = text.index(TOKEN)
    return text[:at], text[at:]


def marked(text: str) -> bool:
    return count(text) == 1


def has_context(text: str) -> bool:
    """Has Jarvis written anything into this note yet?

    A migrated note that nobody has appended to has a marker and a heading and
    nothing else. That is not context, and treating it as such would make the
    rebuild guard refuse a vault where Jarvis has done nothing.
    """
    try:
        _, below = split(text)
    except MarkerError:
        return False
    body = below.split("-->", 1)[-1] if "-->" in below else below
    return not _EMPTY_BELOW.match(body)


def split_bytes(data: bytes) -> tuple[bytes, bytes]:
    """(above, below), on bytes. The write path's only splitter.

    Same rule as `split`, on the representation that has not been through a
    translating reader.
    """
    found = data.count(TOKEN_BYTES)
    if found == 0:
        raise MarkerError(
            f"no {TOKEN!r} marker in this note. Jarvis appends below the marker and "
            "will not create one on the fly: a note with no marker is a note this does "
            "not understand. Run: ranger accounts migrate"
        )
    if found > 1:
        raise MarkerError(
            f"{found} {TOKEN!r} markers in this note, and there must be exactly one. "
            "Two markers means two places to append and no way to tell which half is "
            "the export."
        )
    at = data.index(TOKEN_BYTES)
    return data[:at], data[at:]


def digest(data: bytes) -> str:
    """Of the bytes above the marker. The thing the append guard compares.

    Bytes only, and a string is a TypeError rather than a quiet encode. A
    digest taken over a decoded string is a digest of something that has
    already been through a reader that may have rewritten every line ending,
    which is exactly how this went wrong the first time.
    """
    if not isinstance(data, (bytes, bytearray)):
        raise TypeError(
            f"digest takes bytes, not {type(data).__name__}. The account write path is "
            "binary end to end on purpose: hashing a decoded string hashes whatever "
            "the reader did to it."
        )
    return hashlib.sha256(bytes(data)).hexdigest()


def newline_of(data: bytes) -> bytes:
    """The line ending this file already uses.

    So a CRLF note does not grow LF-only lines. Harmless to render, ugly in
    every future diff, and avoidable in one line. Jarvis matches what is there
    and never converts what is already written.
    """
    if b"\r\n" in data:
        return b"\r\n"
    if b"\r" in data and b"\n" not in data:
        return b"\r"
    return b"\n"


def as_bytes(text: str, newline: bytes = b"\n") -> bytes:
    """Text Jarvis is adding, encoded with the endings the file already uses.

    Only ever applied to newly composed text. Bytes that were already on disk
    are never passed through this.
    """
    encoded = text.encode("utf-8")
    return encoded.replace(b"\n", newline) if newline != b"\n" else encoded


#: A dated context line under an entry. **Every one of these carries its own
#: date**, because the entry's date says when it was written and says nothing
#: about when what it contains was true.
CONTEXT_LINE = "- {when}: {what} ({source})"


def entry_with_context(
    note: str,
    source: str,
    context: "list[tuple[str, str, str]] | None" = None,
    when: date | None = None,
) -> str:
    """One appended block: the operator's words, then anything added, dated.

    **What the operator said and what Jarvis added are not the same sentence.**
    A note that blends them reads as one statement from the operator, and the
    added half is the half nobody can check. So the operator's line is the
    entry, and everything Jarvis knew already goes underneath it, one item at a
    time, each with the date it was true and where it came from.

    The failure this is shaped against was real and was not invention: a true
    fact from months earlier, filed in the present tense with no date, reading
    as the current state of the account. Worse than a wrong fact, because it is
    credible and it compounds -- it is read every day and becomes the input to
    everything concluded later.
    """
    block = entry(note, source, when)
    if not context:
        return block
    lines = [
        CONTEXT_LINE.format(
            when=" ".join(str(item_when).split()),
            what=" ".join(str(what).split()),
            source=" ".join(str(item_source).split()) or "Jarvis",
        )
        for item_when, what, item_source in context
    ]
    return block + "\n".join(lines) + "\n"


def entry(note: str, source: str, when: date | None = None) -> str:
    """One appended block, in the format the note already uses.

    Newlines are stripped out of the heading rather than escaped: a note
    containing one would produce a second heading and a fragment that parses as
    a different activity.
    """
    line = ENTRY.format(
        when=(when or date.today()).isoformat(),
        note=" ".join(str(note).split()),
        source=" ".join(str(source).split()),
    )
    return f"\n{line}\n"


# -- the migration ----------------------------------------------------------


@dataclass
class Migration:
    """What a run did, and what it refused to touch."""

    migrated: list[str] = field(default_factory=list)
    already: list[str] = field(default_factory=list)
    refused: list[tuple[str, str]] = field(default_factory=list)

    @property
    def changed(self) -> int:
        return len(self.migrated)

    def describe(self) -> str:
        lines = [
            f"{len(self.migrated)} migrated, {len(self.already)} already marked",
        ]
        for name, why in self.refused:
            lines.append(f"  refused {name}: {why}")
        return "\n".join(lines)


def migrate(vault: Any, folder: Path, *, dry_run: bool = False) -> Migration:
    """Append the marker to every account note that has not got one.

    Idempotent by construction: a note is migrated only when it has exactly zero
    markers, so a second run finds one everywhere and does nothing. A note with
    two is refused rather than repaired, because there is no way to know which
    of them the operator meant.
    """
    report = Migration()
    for note in sorted(folder.rglob("*.md")):
        if not note.is_file():
            continue
        name = note.name
        try:
            # Binary, like the append path and for the same reason: reading
            # text and writing text would rewrite every line ending in the CRM
            # half, silently modifying the exact thing the marker exists to
            # protect, before the marker even exists.
            data = note.read_bytes()
        except OSError as exc:
            report.refused.append((name, f"could not be read: {exc}"))
            continue

        found = data.count(TOKEN_BYTES)
        if found == 1:
            report.already.append(name)
            continue
        if found > 1:
            report.refused.append((name, f"{found} markers already"))
            continue

        if not dry_run:
            newline = newline_of(data)
            blank = newline * 2
            separator = b"" if data.endswith(blank) else newline if data.endswith(newline) else blank
            # Append. The bytes already on disk are never rewritten, only added to.
            note.write_bytes(data + separator + as_bytes(BLOCK, newline))
        report.migrated.append(name)
    return report


# -- what is actually in the vault ------------------------------------------


#: The order they are reported in: the two ordinary answers, then the two worth
#: looking at.
STYLES = ("lf", "crlf", "cr", "mixed", "none")


def ending_style(data: bytes) -> str:
    """Which line endings this note uses, or "mixed" if it uses more than one.

    Counted rather than sniffed from the first line. A file whose first hundred
    lines are CRLF and whose last ten are LF is mixed, and mixed is the answer
    worth seeing: the vault came out of four separate CRM exports and nothing
    guarantees they agreed.
    """
    crlf = data.count(b"\r\n")
    lone_cr = data.count(b"\r") - crlf
    lone_lf = data.count(b"\n") - crlf

    present = [
        name
        for name, found in (("crlf", crlf), ("cr", lone_cr), ("lf", lone_lf))
        if found
    ]
    if not present:
        return "none"
    return present[0] if len(present) == 1 else "mixed"


@dataclass
class Endings:
    """The census. What is being migrated, before it is migrated."""

    counts: dict[str, int] = field(default_factory=dict)
    #: Named, because a mixed note is the one the operator may want to look at.
    mixed: list[str] = field(default_factory=list)
    unreadable: list[str] = field(default_factory=list)

    @property
    def total(self) -> int:
        return sum(self.counts.values())

    def lines(self) -> list[str]:
        """One line per style that actually occurs, plus the names worth seeing."""
        out = [
            f"{self.counts[name]} {name.upper() if name != 'mixed' else 'mixed'}"
            for name in STYLES
            if self.counts.get(name)
        ]
        rendered = [f"  line endings: {', '.join(out)}" if out else "  line endings: none"]
        for name in self.mixed[:5]:
            rendered.append(f"    mixed: {name}")
        if len(self.mixed) > 5:
            rendered.append(f"    ... and {len(self.mixed) - 5} more mixed")
        for name in self.unreadable:
            rendered.append(f"    unreadable: {name}")
        return rendered


def survey_endings(folder: Path) -> Endings:
    """Every account note, by the line endings it uses.

    Jarvis never converts what is already on disk, so this changes nothing and
    decides nothing. It is here because the operator asked what they were about
    to migrate, and a mixed count above zero is worth knowing before rather
    than after.
    """
    census = Endings(counts={name: 0 for name in STYLES})
    for note in sorted(folder.rglob("*.md")):
        if not note.is_file():
            continue
        try:
            data = note.read_bytes()
        except OSError:
            census.unreadable.append(note.name)
            continue
        style = ending_style(data)
        census.counts[style] += 1
        if style == "mixed":
            census.mixed.append(note.name)
    return census


# -- the rebuild guard ------------------------------------------------------


def notes_with_context(folder: Path) -> list[tuple[str, int]]:
    """Every account note holding Ranger context, with how many lines of it.

    What `build_vault.py` has to consult before it regenerates anything. The
    operator's intention not to rebuild is the safety property today, and
    intention is not enforcement: every real bug in this build came from
    something that was true by intent rather than in code.
    """
    holding: list[tuple[str, int]] = []
    for note in sorted(folder.rglob("*.md")):
        if not note.is_file():
            continue
        try:
            text = note.read_bytes().decode("utf-8", errors="replace")
        except OSError:
            # Unreadable counts as holding. Fail closed: a note that cannot be
            # checked is not a note that has been cleared.
            holding.append((note.name, -1))
            continue
        if not has_context(text):
            continue
        _, below = split(text)
        body = below.split("-->", 1)[-1] if "-->" in below else below
        holding.append((note.name, len([ln for ln in body.splitlines() if ln.strip()])))
    return holding


def rebuild_refusal(folder: Path) -> str:
    """The message build_vault.py prints instead of running, or "" to proceed."""
    holding = notes_with_context(folder)
    if not holding:
        return ""
    lines = [
        f"REFUSING to rebuild: {len(holding)} account notes hold Ranger context "
        "below the marker, and a rebuild would destroy it.",
        "",
    ]
    for name, count_of in holding[:10]:
        detail = "unreadable" if count_of < 0 else f"{count_of} lines"
        lines.append(f"  {name}  ({detail})")
    if len(holding) > 10:
        lines.append(f"  ... and {len(holding) - 10} more")
    lines += [
        "",
        "Nothing above the marker is at risk; everything below it is. If you have",
        "decided to lose it, pass --rebuild-destroys-ranger-notes and confirm at",
        "the prompt.",
    ]
    return "\n".join(lines)
